### ISSUE TITLE
Ability to install globally or in custom user path

### ISSUE THREAD

**Issue by lowlydba** [potatoqualitee/psmodulecache#15]
Thanks for the awesome action!

I'm working on a somewhat sticky CI build out (https://github.com/lowlydba/lowlydba.sqlserver/pull/24) where a WSL user will be remoting into the Windows runner under a different user, and then utilizing dbatools from that session. 

Since the module gets saved right now in the `C:\Users\runneradmin\Documents\WindowsPowerShell\Modules` directory, it won't be accessible to other users. If the action could have the option to choose a globally recognized install location, or specify an alternate user directory, it would be more flexible for complex scenarios like this.

**Comment by briantist** [comment]
Looks like we both had the same idea basically haha
- #16
