### ISSUE TITLE
[For information] Case of module dependencies that cannot be handled by PsModuleCache.

### ISSUE THREAD

**Issue by LaurentDardenne** [potatoqualitee/psmodulecache#27]
During my tests I used the ImportExcel module under Windows, in this case there are no dependencies, but under **Linux** and **MacOs** the module displays the following warning:

With MacOs :
![image](https://user-images.githubusercontent.com/4894452/182624743-84a1b49a-c54f-4073-bd2a-fd0065e70e54.png)

With  Ubuntu : 
![image](https://user-images.githubusercontent.com/4894452/182628844-68134840-9229-4d79-9faf-c3f2ccb84b62.png)

PSModuleCache targeting only packages created via Publish-Module and saved via Save-Module, this case is not taken into account.

**Comment by potatoqualitee** [comment]
hey Laurent, this seems out of scope for my project. I'd recommend using the cacher in your workflow to cache the packages or install the packages manually prior to the psmodulecache step.

**Comment by LaurentDardenne** [comment]
> this seems out of scope for my project.

I know, as I have encountered the case as far as others know.
And since the dependencies, managed by Publish-Module, must be in the same repository, that doesn't change much.
