### ISSUE TITLE
Action parameters of boolean type are not correctly typed

### ISSUE THREAD

**Issue by LaurentDardenne** [potatoqualitee/psmodulecache#28]
Action parameters of boolean type are not correctly typed :
```powershell
[bool]'false'
#True
```
This causes erroneous behavior.

When fixed, setting Force to $False raises an exception :
![image](https://user-images.githubusercontent.com/4894452/183071692-3cf5b9f5-9d24-4b48-8050-fc9ec1b78dfb.png)

According to the message the -Force parameter of Save-Module should still be present but no longer be used in the action parameters, because if the parameter is false [the requested path is not created if it does not exist](https://github.com/PowerShell/PowerShellGetv2/blob/master/src/PowerShellGet/public/psgetfunctions/Save-Module.ps1#L136).
And the documentation for this setting on[ MS Doc seems wrong](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9094).

**Comment by potatoqualitee** [comment]
thanks for finding this! would you like to submit a PR and i can do a release?

**Comment by LaurentDardenne** [comment]
>would you like to submit a PR 

Yes, that said I rewrote the Action around [a module](https://github.com/PSLDA/psmodulecache/blob/main/action.yml#L37)

In a few hours I will post a summary, from there you will tell me if you want to use this version or not.

**Comment by potatoqualitee** [comment]
awesome, thank you!

**Comment by LaurentDardenne** [comment]
Fixed in Vnext.
