### ISSUE TITLE
Two warnings about command deprecated

### ISSUE THREAD

**Issue by niheaven** [potatoqualitee/psmodulecache#35]
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

> Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by potatoqualitee** [comment]
oh wow, thank you i didnt see this ill check it out /cc @LaurentDardenne

**Comment by LaurentDardenne** [comment]
I think the modifications are minimal, they depend on a possible modification of [this](https://github.com/potatoqualitee/psmodulecache/blob/main/action.yml#L65).

I don't know if [this](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#using-the-output-of-the-cache-action) will also change.

I will test this soon

**Comment by LaurentDardenne** [comment]
In the 'action.yml' file we must modify three lines including the version number of 'actions/cache' :
```Powershell
        #Write-Output "::set-output name=keygen::$($ModulesCache.Key)"
        echo "{keygen}={$($ModulesCache.Key)}" >> $GITHUB_OUTPUT

        $Paths=@(New-ModuleSavePath $ModulesCache.ModuleCacheInformations)

        #Write-Output "::set-output name=modulepath::$(ConvertTo-YamlLineBreak $Paths)"
        echo "{modulepath}={$(ConvertTo-YamlLineBreak $Paths)}" >> $GITHUB_OUTPUT
        $null = $ModulesCache | Export-CliXml -Path (Join-Path $home -ChildPath $CacheFileName)

    - name: Run module cacher action
      id: cacher
      uses: actions/cache@v3.0.11
```
Then in the workflows, you have to change the 'actions/checkout' version to v2.5.0 (following a NodeJS version change), but I haven't yet understood why there are two active versions in [the releases](https://github.com/actions/checkout/releases) (V2 .5.0 and v3.1.0)

**Comment by niheaven** [comment]
Hi guys, when will this be fixed (along with node 12)? Many thanks!

**Comment by potatoqualitee** [comment]
I'm currently knee deep in huge library changes on another one of my modules and probably won't be able to get around to it for 1-2 weeks but I am open to a PR.

Also, please use "everyone" in lieu of "guys". Merci 🫶

**Comment by potatoqualitee** [comment]
JK! I have to add a dependency so I'm going to update this one too if the tests pass after making @LaurentDardenne's suggested changes

**Comment by potatoqualitee** [comment]
I sincerely hope the laugh response wasn't because I asked you not to address me as a guy.

I have updated the modules and all the tests pass. Turns out, I needed to use `$env:GITHUB_OUTPUT` instead of `$GITHUB_OUTPUT`. I'll be updating GitHub's documentation as well.

**Comment by niheaven** [comment]
Thanks very much for the work @potatoqualitee! And I apologize for the word... As a non-native English speaker, I'm thinking 'guys' is gender-neutral until I googled it 😭 . Since in my native language a masculine noun could be used to refer men, women or any mix-group, I didn't pay much attention to gender neutrality of words or sentences. Very sorry and thanks again!

**Comment by potatoqualitee** [comment]
Thank you for the response, @niheaven 😊
