### ISSUE TITLE
Does not support packages that require the user to accept licenses.

### ISSUE THREAD

**Issue by WiehanVanNiekerk** [potatoqualitee/psmodulecache#59]
Good day. 

I love this package; it's really awesome. I'm currently having an issue with the `SqlChangeAutomation` module. 

It's giving me an error and not performing the accept license operation. 
Is there any option to do that in this action?

![image](https://github.com/potatoqualitee/psmodulecache/assets/53100080/c3996df9-a0e5-4e3d-8cf7-730e0b0e8c78)

```console
- name: Install and cache PowerShell modules
          id: psmodulecache
          uses: potatoqualitee/psmodulecache@v6.0
          with:
            modules-to-cache: dbatools:1.0.0, SqlChangeAutomation
            shell: powershell
```

**Comment by LaurentDardenne** [comment]
Good catch !
Indeed I haven't tested this case, like others...

>>Is there any option to do that in this action?

No, for the moment the installation of this type of module must be done upstream in a dedicated step.
I think the default for all modules to install should be _**-AcceptLicense:$true**_

I also need to test a module which does not require license acceptance but which has a dependency requiring acceptance. I'm not sure if this setting is propagated for all dependencies.

**Comment by LaurentDardenne** [comment]
Done.
[See](https://github.com/potatoqualitee/psmodulecache/tree/v6.1?tab=readme-ov-file#acceptancelicense)
