### ISSUE TITLE
Action generates the same key for MacOs and Ubuntu runners

### ISSUE THREAD

**Issue by cdhunt** [potatoqualitee/psmodulecache#7]
When I was running a matrix test against Windows, Ubuntu and macOS, I found that there was a key collision between Ubuntu and macOS, and the upload of whichever finished last would fail. I experienced inconsistent downloads of the cache after that, though I can't be sure if the key collision was the root cause. I prefixed the key with the GitHub Actions variable `${{ runner.os }}` to get a more unique string.

If someone addresses this, I'd also like to suggest adding an optional (is that possible?) input that acts as a cache breaker. I found a bug in my Install-Modules snippet would create a useless cache that builds then try to reuse. Adding a user-defined int or datetime as part of the keygen would let me create a new cache when the `modules-to-cache` doesn't actually change.

**Comment by potatoqualitee** [comment]
Thank you! I fixed this in v1.1 (but have not yet added support for RequiredVersion, it's on my todo)
